// ==UserScript==
// @name         Claude Automation - senior_care_short
// @namespace    http://tampermonkey.net/
// @version      1.0.1
// @description  시니어 케어 숏폼 대본 생성
// @author       Atobro
// @match        https://claude.ai/project/019b085a-4903-7726-a10a-11b83da590cd
// @updateURL    https://cdn.jsdelivr.net/gh/elbenze92-cell/ts-x7k9m2p4@main/senior_care_short.user.js
// @downloadURL  https://cdn.jsdelivr.net/gh/elbenze92-cell/ts-x7k9m2p4@main/senior_care_short.user.js
// @grant        GM_addStyle
// @run-at       document-end
// ==/UserScript==

(function() {
    'use strict';
    console.log('💊 Senior Care Short 시작');
    let isRunning = false, currentStep = 0, allResponses = [];
    const MAX_STEPS = 7;

    const STEP_PROMPTS = [
        { name: "기승전결 패턴 학습", prompt: `1단계: 시니어 건강 기승전결 패턴 학습\n당신은 시니어(50-70대) 건강 전문 숏폼 제작자입니다.\n\n패턴 A - 증상 공감형: 기(증상 제시) → 승(악화 사례) → 전(의학적 설명) → 결(대응법)\n패턴 B - 상식 깨기형: 기(흔한 믿음) → 승(전문의 반대) → 전(연구 결과) → 결(올바른 방법)\n패턴 C - 질병 신호형: 기(사소한 변화) → 승(위험 신호) → 전(질병 연관성) → 결(체크리스트)\n\n핵심 원칙: 의료법 준수, 희망적 톤, 전문의 상담 권장\n이해했으면 '패턴 학습 완료'`},
        { name: "콘텐츠 특성 학습", prompt: `2단계: 시니어 건강 특성 학습\n\n타겟: 50-70대 건강 관심층\n터지는 주제: 만성질환, 통증, 노화증상, 소화/수면, 예방\n후킹: "무릎이 시큰거리시나요?", "이 증상 방치하면 위험", "왜 약 먹어도 안 나을까요?"\n금지: 특정 약물 언급, "낫는다" 보장, 병원 치료 대체 암시\n필수: 전문의 조언, "개인차 있음" 명시, 희망적 마무리\n\n이해했으면 '특성 학습 완료'`},
        { name: "주제 선택", prompt: `3단계: 건강 주제 선택\n\n주제 풀:\n근골격계: 무릎통증, 허리디스크, 골다공증, 어깨오십견\n대사/순환기: 고혈압약, 당뇨초기증상, 콜레스테롤, 혈액순환\n소화/영양: 속쓰림, 변비, 영양제과다, 식후졸음\n뇌/신경: 치매vs건망증, 어지럼증, 손발저림, 불면증\n\n하나 선택 후 형식 출력:\n【선택한 주제】:\n【선택 이유】:\n【적용 패턴】: A~C\n【타겟 감정】: 공감/경각심/안심\n【예상 후킹】:`},
        { name: "구조 설계", prompt: `4단계: 40-50초 구조 설계\n\n기(0-8초): 시니어 공감 증상 제시\n승(8-20초): 대수롭지 않게 여기다 악화\n전(20-40초): 전문의 설명, 대응법\n결(40-50초): 희망적 메시지, 전문의 상담 권장\n\n구조표 작성 후 초안 대본 작성\n의료법 체크: □ 보장표현 없음 □ 전문의 상담 포함 □ "개인차" 명시`},
        { name: "3개 버전 생성", prompt: `5단계: 3개 버전 생성\n\n말투: "~했습니다/~했는데요" 번갈아, 쉼표/마침표 금지, 400-550자\n\n버전 1: 증상 공감형\n【후킹】:\n【와우】:\n【대본】:\n\`\`\`\n(내용)\n\`\`\`\n\n버전 2: 전문의 인용형\n버전 3: 예방 실천형`},
        { name: "최종 선택", prompt: `6단계: 최종 대본 선택\n\n선택 기준: 시니어 공감도, 의학 정확성, 희망적 메시지, 의료법 준수\n검증: □ 가이드라인 위반 없음 □ 허위정보 없음 □ 글자수 적정 □ CTA 자연스러움\n\nCTA 예시: "건강 정보 도움되셨다면 좋아요", "전문의 상담 꼭 받으세요"\n\n최종 선택 버전과 수정사항, 검증결과, 최종 대본 출력`},
        { name: "최종 출력", prompt: `7단계: 최종 출력\n\n⛔ 마커 밖 텍스트 금지\n\n---SCRIPT_START---\n(최종 대본 전체)\n---SCRIPT_END---\n\n---PROMPTS_START---\n1. Elderly Korean person feeling knee pain, realistic photo, concerned expression, home interior, 9:16\n2. Medical illustration knee joint inflammation, educational style, professional diagram, 9:16\n3. Korean senior at doctor consultation, friendly doctor with tablet, modern clinic, 9:16\n4. Senior doing gentle knee exercises, peaceful home, healthy lifestyle, soft light, 9:16\n5. Healthy food for joint health, colorful vegetables supplements, overhead view, 9:16\n6. Senior walking pain-free in park, sunrise, recovery concept, cinematic, 9:16\n7. Hands holding medical report positive results, relief hope, intimate lighting, 9:16\n8. Senior smiling while exercising, active lifestyle, inspiring, golden hour, 9:16\n9. Traditional herbal modern medicine together, holistic health, 9:16\n10. Senior couple walking happily, healthy aging, warm afternoon, emotional, 9:16\n---PROMPTS_END---`}
    ];

    GM_addStyle(`#script-automation-panel{position:fixed;top:20px;right:20px;width:420px;background:linear-gradient(135deg,#FF6B9D,#FFA06B);color:white;padding:25px;border-radius:16px;box-shadow:0 8px 24px rgba(0,0,0,0.15);z-index:10000;font-family:'Segoe UI',sans-serif}#script-automation-panel h3{margin:0 0 15px 0;font-size:19px;text-align:center;font-weight:600}.category-badge{background:rgba(255,255,255,0.3);padding:6px 18px;border-radius:20px;font-size:11px;display:inline-block;margin-bottom:15px;font-weight:600}.step-counter{text-align:center;font-size:20px;font-weight:600;margin:15px 0;padding:14px;background:rgba(255,255,255,0.2);border-radius:10px}.step-name{font-size:12px;opacity:0.85;margin-top:6px}#start-btn,#stop-btn{width:100%;padding:16px;font-size:15px;font-weight:600;border:none;border-radius:10px;cursor:pointer;margin-bottom:10px;transition:all 0.3s}#start-btn{background:linear-gradient(135deg,#10B981,#34D399);color:white;box-shadow:0 4px 14px rgba(16,185,129,0.4)}#start-btn:disabled{background:#999;cursor:not-allowed;opacity:0.5}#stop-btn{background:linear-gradient(135deg,#FF6B6B,#EE5A6F);color:white;display:none}#download-btn{width:100%;padding:16px;background:linear-gradient(135deg,#3498db,#2980b9);color:white;border:none;border-radius:10px;cursor:pointer;font-weight:600;margin-bottom:10px}#download-btn:disabled{background:#999;opacity:0.5}.progress-bar{width:100%;height:6px;background:rgba(255,255,255,0.2);border-radius:3px;margin:12px 0}.progress-fill{height:100%;background:linear-gradient(90deg,#10B981,#34D399);width:0%;transition:width 0.5s}#automation-status{background:rgba(0,0,0,0.15);padding:12px;border-radius:10px;margin-top:12px;font-size:12px;max-height:160px;overflow-y:auto}.status-line{margin:4px 0;padding:6px 8px;background:rgba(255,255,255,0.1);border-radius:6px;font-size:11px;line-height:1.4}.status-line.success{background:rgba(16,185,129,0.3)}.status-line.error{background:rgba(255,107,107,0.25)}`);

    function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
    function addStatus(msg,type='normal'){const s=document.getElementById('automation-status');if(!s)return;const l=document.createElement('div');l.className=`status-line ${type}`;l.textContent=`[${new Date().toLocaleTimeString()}] ${msg}`;s.insertBefore(l,s.firstChild);while(s.children.length>15)s.removeChild(s.lastChild);console.log(msg)}
    function updateStepDisplay(){const sc=document.getElementById('step-count'),sn=document.getElementById('step-name'),pf=document.getElementById('progress-fill');if(sc)sc.textContent=`${currentStep}/${MAX_STEPS}`;if(sn&&currentStep>0&&currentStep<=MAX_STEPS)sn.textContent=STEP_PROMPTS[currentStep-1].name;if(pf)pf.style.width=`${(currentStep/MAX_STEPS)*100}%`}
    function isClaudeResponding(){return!!document.querySelector('button[aria-label="Stop response"]')||!!document.querySelector('button[aria-label="응답 중단"]')}
    async function waitForResponseComplete(maxWait=1800000){const start=Date.now();addStatus('⏳ 응답 대기');let started=false;for(let i=0;i<40;i++){if(isClaudeResponding()){started=true;addStatus('✍️ 응답 중');break}await sleep(500)}if(!started){addStatus('✅ 응답 완료');await sleep(2000);return true}let cnt=0;while(isClaudeResponding()){const elapsed=Date.now()-start;if(elapsed>maxWait)throw new Error('타임아웃');cnt++;if(cnt%30===0){const m=Math.floor(elapsed/60000),s=Math.floor((elapsed%60000)/1000);addStatus(`⏳ 대기 중 (${m}분 ${s}초)`)}await sleep(1000)}addStatus('✅ 응답 완료!','success');await sleep(2000);return true}
    async function inputPrompt(promptText,maxRetries=5){for(let attempt=1;attempt<=maxRetries;attempt++){try{addStatus(`[${attempt}/${maxRetries}] 전송 시도`);const inputField=document.querySelector('div.ProseMirror[contenteditable="true"]');if(!inputField)throw new Error('입력 필드 없음');inputField.focus();inputField.click();await sleep(200);inputField.innerHTML='';promptText.split('\n').forEach((line,i)=>{if(line.trim()){const p=document.createElement('p');p.textContent=line;inputField.appendChild(p)}else if(i<promptText.split('\n').length-1)inputField.appendChild(document.createElement('br'))});inputField.dispatchEvent(new Event('input',{bubbles:true}));await sleep(500);let sendButton=document.querySelector('button[aria-label="Send message"]');if(!sendButton){sendButton=Array.from(document.querySelectorAll('button')).find(btn=>{const svg=btn.querySelector('svg'),path=svg?.querySelector('path'),d=path?.getAttribute('d');return d?.includes('M208.49,120.49')})}if(!sendButton||sendButton.disabled)throw new Error('전송 버튼 없음');sendButton.click();addStatus('✅ 전송 성공!','success');await waitForResponseComplete();return true}catch(error){addStatus(`⚠️ 실패: ${error.message}`,'error');if(attempt<maxRetries){await sleep(attempt*2000)}else throw error}}}
    function collectResponse(){try{const responses=document.querySelectorAll('div[class*="font-claude-response"]');if(currentStep===MAX_STEPS){for(let i=responses.length-1;i>=0;i--){const txt=responses[i].innerText.trim();const ss='---SCRIPT_START---',se='---SCRIPT_END---',ps='---PROMPTS_START---',pe='---PROMPTS_END---';if(txt.includes(ss)&&txt.includes(se)){const script=txt.substring(txt.indexOf(ss)+ss.length,txt.indexOf(se)).trim();let prompts=[];if(txt.includes(ps)&&txt.includes(pe)){const ptxt=txt.substring(txt.indexOf(ps)+ps.length,txt.indexOf(pe)).trim();prompts=ptxt.split(/\n?\d+\.\s*/).map(l=>l.trim()).filter(l=>l.length>10);if(prompts.length<5)prompts=ptxt.split('\n').map(l=>l.trim()).filter(l=>l.length>20)}localStorage.setItem('FINAL_SCRIPT',script);window.FINAL_SCRIPT_FOR_PYTHON=script;if(prompts.length>0){localStorage.setItem('IMAGE_PROMPTS',JSON.stringify(prompts));window.IMAGE_PROMPTS=prompts;localStorage.setItem('MOTIVATION_SCRIPT_JSON',JSON.stringify({image_prompts:prompts}))}return script}}}if(responses.length>0){const last=responses[responses.length-1];return last.innerText.trim()}return ''}catch(e){console.error(e);return ''}}
    function createPanel(){const panel=document.createElement('div');panel.id='script-automation-panel';panel.innerHTML=`<h3>💊 시니어 케어 숏폼</h3><div style="text-align:center;"><span class="category-badge">HEALTH CARE</span></div><div class="step-counter">단계: <span id="step-count">0/7</span><div class="step-name" id="step-name">대기 중</div></div><div class="progress-bar"><div class="progress-fill" id="progress-fill"></div></div><button id="start-btn">🚀 대본 생성 시작</button><button id="stop-btn">⏹ 중지</button><button id="download-btn" disabled>✅ 작업 완료</button><div id="automation-status"></div>`;document.body.appendChild(panel);document.getElementById('start-btn').addEventListener('click',startGeneration);document.getElementById('stop-btn').addEventListener('click',stopGeneration)}
    async function startGeneration(){isRunning=true;currentStep=0;allResponses=[];document.getElementById('start-btn').style.display='none';document.getElementById('stop-btn').style.display='block';document.getElementById('download-btn').disabled=true;addStatus('🚀 생성 시작!','success');function keepAlive(){if(isRunning)requestAnimationFrame(keepAlive)}keepAlive();while(isRunning&&currentStep<MAX_STEPS){const step=STEP_PROMPTS[currentStep];currentStep++;updateStepDisplay();addStatus(`📝 ${currentStep}단계: ${step.name}`);try{const success=await inputPrompt(step.prompt);if(!success){addStatus(`❌ ${step.name} 실패`,'error');await sleep(3000);currentStep--;continue}await sleep(2000);let cc=0;while(cc<2){const cont=await handleContinue();if(cont){cc++;await waitForResponseComplete()}else break}const res=collectResponse();allResponses.push({step:`${currentStep}. ${step.name}`,response:res});addStatus(`✅ ${step.name} 완료`,'success')}catch(e){addStatus(`⚠️ 오류: ${e.message}`,'error');await sleep(5000);currentStep--}await sleep(3000)}stopGeneration()}
    async function handleContinue(){await sleep(2000);const btn=Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes('Continue')||b.textContent.includes('계속'));if(btn){btn.click();addStatus('✅ Continue 클릭');return true}return false}
    function stopGeneration(){isRunning=false;document.getElementById('start-btn').style.display='block';document.getElementById('stop-btn').style.display='none';if(currentStep>=MAX_STEPS){addStatus('🎉 생성 완료!','success');document.getElementById('download-btn').disabled=false}}
    function init(){if(!document.body){setTimeout(init,1000);return}const existing=document.getElementById('script-automation-panel');if(existing)existing.remove();try{createPanel();addStatus('✅ 준비 완료')}catch(e){console.error(e)}}
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){const p=document.getElementById('script-automation-panel');if(p)p.style.display=p.style.display==='none'?'block':'none'}});
    function waitForPageLoad(){const body=document.body,main=document.querySelector('main');if(body&&main&&(document.readyState==='interactive'||document.readyState==='complete')){setTimeout(()=>{init();setTimeout(()=>{if(!document.getElementById('script-automation-panel'))init()},500)},2000)}else setTimeout(waitForPageLoad,500)}
    waitForPageLoad()
})();

(function(){'use strict';function killPopup(){document.querySelectorAll('[role="dialog"]').forEach(d=>{if((d.textContent||'').includes('Claude를 계속')||(d.textContent||'').includes('Continue using'))d.remove()});document.body.style.overflow=''}const obs=new MutationObserver(killPopup);obs.observe(document.body,{childList:true,subtree:true});setInterval(killPopup,2000)})();
